---
# Main playbook

- name: Deploy and configure webservers
  become: yes
  hosts: webservers
  roles:
    - web
  vars_files:
  - roles/web/vars/private/linuxusers.yml
  - roles/web/vars/private/apachevhosts.yml

- name: Deploy database servers
  become: yes
  hosts: dbservers
  roles:
    - db

- name: Deploy mailservers
  become: yes
  hosts: mailservers
  roles:
    - mail