---
# Main playbook

- name: Deploy and configure webservers
  become: yes
  hosts: webservers
  roles:
    - web

- name: Deploy database servers
  become: yes
  hosts: dbservers
  roles:
    - db

- name: Deploy mailservers
  become: yes
  hosts: mailservers
  roles:
    - mail