---
- name: Deploy and configure web01.whservice.nl
  become: yes
  hosts: webservers
  roles:
    - basic
    - web
  vars_files:
    - roles/basic/vars/private/linuxusers.yml

- name: Deploy database server on web01.whservice.nl
  become: yes
  hosts: dbservers
  roles:
    - db

- name: Deploy mailserver on web01.whservice.nl
  become: yes
  hosts: mailservers
  roles:
    - mail
  vars_files:
    - roles/mail/vars/private/mailvars.yml
