---
# Main webserver handler tasks

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: restart vsftp
  service:
    name: vsftpd
    state: restarted

- name: "restart php 7.4"
  service:
    name: php7.4-fpm
    state: restarted

- name: setup iptables dns
  replace:
    path: /usr/local/bin/start_firewall.sh
    regexp: "PUT_DNS_SERVERS_HERE"
    replace: "{{ dns_servers }}"
  notify: start firewall

- name: start firewall
  command:
    cmd: bash /usr/local/bin/start_firewall.sh

- name: create documentroots
  file:
    path: "{{ item.value.documentroot }}"
    owner: "{{ item.value.docroot_owner }}"
    group: "{{ item.value.docroot_owngroup }}"
    state: directory
  with_dict: "{{ apache_vhosts }}"

- name: load apache vhosts
  shell:
    chdir: /etc/apache2/sites-available
    cmd: a2ensite *.conf