---
# Main webserver handler tasks

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: setup iptables dns
  replace:
    path: /usr/local/bin/start_firewall.sh
    regexp: "PUT_DNS_SERVERS_HERE"
    replace: "{{ dns_servers }}"
  notify: start firewall

- name: start firewall
  command:
    cmd: bash /usr/local/bin/start_firewall.sh