---
# Main webserver handler tasks

- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: "restart php 7.4"
  service:
    name: php7.4-fpm
    state: restarted

- name: "restart php 7.3"
  service:
    name: php7.3-fpm
    state: restarted

- name: setup iptables dns
  replace:
    path: /usr/local/bin/start_firewall.sh
    regexp: "PUT_DNS_SERVERS_HERE"
    replace: "{{ dns_servers }}"
  notify: start firewall

- name: start firewall
  command:
    cmd: bash /usr/local/bin/start_firewall.sh