---

- name: Copy custom SSH config file over
  copy:
    src: sshd_custom.conf
    dest: /etc/ssh/sshd_config.d/custom.conf
    mode: 0644
    owner: root
    group: root

- name: Make sure SSH uses custom config file
  lineinfile:
    insertafter: "EOF"
    line: "Include sshd_config.d/custom.conf"
    path: /etc/ssh/sshd_config
    state: present
  notify: restart ssh

- name: Only allow ssh for set users
  replace:
    path: /etc/ssh/sshd_config.d/custom.conf
    regexp: '(?m)^AllowUsers\s([\s\w][^#\n]+)'
    replace: AllowUsers \1 {{ item.name }}
  loop: "{{ linux_users }}"
  when: item.ssh_access == true
  notify: restart ssh
