---
# Main DB tasks

- name: Install MariaDB and Phpmyadmin
  apt:
    pkg:
      - mariadb-server
    state: present

- name: Copy over phpmyadmin installation script
  copy:
    src: roles/db/files/install-phpmyadmin-openlitespeed.sh
    dest: /tmp/install-phpmyadmin-openlitespeed.sh
    mode: 0755
    owner: root
    group: root

- name: Run phpmyadmin installation script
  command: /tmp/install-phpmyadmin-openlitespeed.sh

- name: Copy custom mysql config file over
  copy:
    src: roles/db/files/my.cnf
    dest: /etc/my.cnf
    mode: 0644
    owner: root
    group: root
  notify: restart mysql