---
# Main DB tasks

- name: Install MariaDB and Phpmyadmin
  apt:
    pkg:
      - mariadb-server
      - phpmyadmin
    state: present

- name: Ensure phpMyAdmin config file is included in Apache config.
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    regexp: "^Include.+phpmyadmin.+$"
    line: "Include /etc/phpmyadmin/apache.conf"
    insertafter: "EOF"
  notify: restart apache

- name: Copy custom mysql config file over
  copy:
    src: roles/db/files/my.cnf
    dest: /etc/my.cnf
    mode: 0644
    owner: root
    group: root
  notify: restart mysql