---
# Main DB tasks

- name: Install MariaDB and Phpmyadmin
  apt:
    pkg:
      - mariadb-server
      - phpmyadmin
    state: present

- name: Copy custom mysql config file over
  copy:
    src: roles/db/files/my.cnf
    dest: /etc/my.cnf
    mode: 0644
    owner: root
    group: root
  notify: restart mysql