---
# Configuration file for Z-Push

- name: Install php-mapi package
  apt:
    pkg:
      - php-mapi
      - libawl-php
    state: present

- name: Create a special z-push user
  user:
    name: "zpush"
    state: "present"
    password_lock: "yes"
    system: "yes"
    create_home: "no"

- name: Create a directory for Z-push instances
  file:
    path: /usr/share/z-push
    state: directory
    owner: zpush
    group: zpush
    mode: 0755

- name: Create a directory for Z-push logs
  file:
    path: /var/log/z-push
    state: directory
    owner: zpush
    group: zpush
    mode: 0755

- name: Create a directory for Z-push libraries
  file:
    path: /var/lib/z-push
    state: directory
    owner: zpush
    group: zpush
    mode: 0755

- name: Copy over Z-push clone script
  copy:
    src: roles/mail/files/clone-z-push.sh
    dest: /usr/local/bin/clone-z-push.sh
    mode: 0644
    owner: root
    group: root

- name: Copy over PHP.ini file for Z-push
  copy:
    src: roles/mail/files/z-push-php.ini
    dest: /usr/share/z-push/.user.ini

- name: Install PHP-FPM pool configuration for zpush
  copy:
    src: roles/mail/files/zpush-php-fpm-pool.conf
    dest: /etc/php/7.4/fpm/pool.d/zpush-php-fpm-pool.conf
    mode: 0644
  notify: "restart php 7.4"

- name: Create Z-push directories for all the e-mail domains and clone Z-push in there
  shell:
    chdir: /usr/share/z-push
    cmd: bash /usr/local/bin/clone-z-push.sh {{ item }}
  loop: "{{ emaildomains }}"

- name: Set 'USE_FULLEMAIL_FOR_LOGIN' to true for all Z-push instances
  lineinfile:
    path: /usr/share/z-push/{{ item }}/src/autodiscover/config.php
    regexp: \s{0,4}define\('USE_FULLEMAIL_FOR_LOGIN',\sfalse\);
    line: define('USE_FULLEMAIL_FOR_LOGIN', true);
  loop: "{{ emaildomains }}"

- name: Create autodiscover apache2 configuration for each e-mail domain
  template:
    src: "autodiscover-vhost.conf.j2"
    dest: "/etc/apache2/sites-available/autodiscover.{{ item }}.conf"
  loop: "{{ emaildomains }}"
  notify:
    - load apache vhosts
    - restart apache