---
# Configuration file for SpamAssassin

- name: Configure postfix to connect to SpamAssassin
  shell:
    cmd: |
     postconf smtpd_milters=unix:/spamass/spamass.sock
     postconf non_smtpd_milters=unix:/spamass/spamass.sock
     postconf milter_connect_macros="i j {daemon_name} v {if_name} _"

- name: Configure SpamAssassin to use the vmail's home folder for Bayes
  lineinfile:
    path: /etc/default/spamd
    regexp: OPTIONS="[\w\-\s]+"
    line: OPTIONS="--create-prefs --max-children 5 --helper-home-dir -x -u vmail"

- name: Configure Spamassassin to get user preferences from MySQL
  template:
    src: "spamassassin-sql.cf.j2"
    dest: "/etc/spamassassin/sql.cf"

- name: Configure Bayes to use MySQL
  template:
    src: "bayes-sql.cf.j2"
    dest: "/etc/spamassassin/bayes.cf"

- name: Enable the SpamAssassin update cron
  lineinfile:
    path: /etc/default/spamd
    regexp: CRON\s?=\s?0
    line: CRON=1

- name: Enable the SpamAssassin service
  systemd:
    enabled: yes
    name: spamd
    state: started
  notify: restart spamassassin

- name: Add the SpamAssassin milter user to the spamd group
  user:
    append: yes
    groups: debian-spamd
    name: spamass-milter

- name: Create SpamAssassin systemd override directory
  file:
    path: /etc/systemd/system/spamd.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy SpamAssassin systemd override configuration over
  copy:
    dest: /etc/systemd/system/spamd.service.d/override.conf
    src: roles/mail/files/override-spamassassin-systemd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart spamassassin with daemon reload

- name: Configure Spamass-milter to pass entire e-mail address to spamc
  lineinfile:
    path: /etc/default/spamass-milter
    regexp: OPTIONS\s?=\s?"[\w\.\-\s]+"
    line: OPTIONS="-u spamass-milter -i 127.0.0.1 -e {{ defaultdomain }}"
  notify: restart spamass-milter

