---
# Configuration tasks for OpenDKIM

- name: Copy OpenDKIM configuration file
  copy:
    backup: yes
    dest: /etc/opendkim.conf
    group: root
    owner: root
    src: roles/mail/files/opendkim.conf

- name: Set the correct run directory for opendkim
  lineinfile:
    path: /etc/default/opendkim
    regexp: RUNDIR\s?=\s?[\w\/]+
    line: RUNDIR=/var/run/opendkim

- name: Create OpenDKIM socket directory
  file:
    path: /var/spool/postfix/opendkim/
    state: directory
    owner: opendkim
    group: opendkim
    mode: 0755

- name: Add postfix user to the opendkim group
  user:
    append: yes
    name: postfix
    groups: opendkim
    remove: no
    state: present

- name: Enable opendkim smtpd miltering in Postfix
  replace:
    path: /etc/postfix/main.cf
    regexp: ^smtpd_milters\s?=\s?(unix:\/spamass\/spamass.sock)
    replace: smtpd_milters=\1,unix:/opendkim/opendkim.sock

- name: Enable opendkim non-smtpd miltering in Postfix
  replace:
    path: /etc/postfix/main.cf
    regexp: ^non_smtpd_milters\s?=\s?(unix:\/spamass\/spamass.sock)
    replace: non_smtpd_milters=\1,unix:/opendkim/opendkim.sock

- name: Create directories for OpenDKIM files and tables
  file:
    path: /etc/opendkim/keys
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy OpenDKIM domain setup file
  copy:
    dest: /usr/local/bin/setup_dkim_for_domain.sh
    group: root
    owner: root
    src: roles/mail/files/setup_dkim_for_domain.sh

- name: Setup OpenDKIM TrustedHosts
  template:
    dest: /etc/opendkim/TrustedHosts
    mode: 0644
    owner: root
    group: root
    src: opendkim_TrustedHosts.j2

- name: Setup OpenDKIM KeyTable
  template:
    dest: /etc/opendkim/KeyTable
    mode: 0644
    owner: root
    group: root
    src: opendkim_KeyTable.j2

- name: Setup OpenDKIM SigningTable
  template:
    dest: /etc/opendkim/SigningTable
    mode: 0644
    owner: root
    group: root
    src: opendkim_SigningTable.j2

- name: Setup the host's default domain
  shell:
    cmd: bash /usr/local/bin/setup_dkim_for_domain.sh {{ defaultdomain }}
