---
# Web role tasks

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"

- name: Install Apache and certbot
  apt:
    pkg:
      - apache2
      - certbot
      - vsftpd
    state: present

- name: Enable mod-rewrite
  shell:
    cmd: a2enmod rewrite
  notify: restart apache

- name: Install PHP and some PHP modules
  apt:
    pkg:
      - php-fpm
      - php-curl
      - php-date
      - php-imagick
      - php-imap
      - php-mysql
      - php-zip
    state: present

- include: setup-php-fpm.yml
- include: setup-firewall-ids.yml
- include: manage-users.yml
- include: setup-vsftp.yml

- name: Create site configurations
  template:
    src: "{{ item.value.template | default(apache_vhosts_template) }}"
    dest: "/etc/apache2/sites-available/{{ item.value.servername }}.conf"
  with_dict: "{{ apache_vhosts }}"
  notify:
    - create documentroots
    - load apache vhosts
    - restart apache

- name: Create weekly update cron
  cron:
    name: "Update system every Tuesday night at 23:00"
    user: root
    weekday: "2"
    month: "*"
    minute: "*"
    hour: "23"
    day: "*"
    job: "(apt-get update && apt-get -y upgrade) > /dev/null"
    state: present

- name: Don't allow SSH access for root
  lineinfile:
    insertafter: "EOF"
    line: "PermitRootLogin no"
    path: /etc/ssh/sshd_config
    state: present
  notify: restart ssh

- name: Allow ansible user to SSH
  lineinfile:
    insertafter: "EOF"
    line: "AllowUsers ansible"
    path: /etc/ssh/sshd_config
    state: present
  notify: restart ssh

- name: Only allow ssh for set users
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers\s([\s\w][^#\n]+)'
    replace: AllowUsers \1 {{ item.name }}
  loop: "{{linux_users}}"
  when: item.ssh_access == true
  notify: restart ssh