---
# Web role tasks

- name: Install Apache and certbot
  apt:
    pkg:
      - apache2
      - certbot
    state: present

- name: Install PHP and some PHP modules
  apt:
    pkg:
      - php-fpm
      - php-curl
      - php-date
      - php-imagick
      - php-imap
      - php-mysql
      - php-zip
    state: present

- include: setup-php-fpm.yml

- name: Copy IPtables setup script over
  copy:
    src: roles/web/files/start_firewall.sh
    dest: /usr/local/bin/start_firewall.sh
    mode: 0644
    owner: root
    group: root
  notify: setup iptables dns

- name: Install fail2ban
  apt:
    pkg: 
      - fail2ban
    state: present