---
# Web role tasks

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"

- name: Install Apache and certbot
  apt:
    pkg:
      - apache2
      - certbot
    state: present

- name: Install PHP and some PHP modules
  apt:
    pkg:
      - php-fpm
      - php-curl
      - php-date
      - php-imagick
      - php-imap
      - php-mysql
      - php-zip
    state: present

- include: setup-php-fpm.yml
- include: setup-firewall-ids.yml
- include: manage-users.yml

- name: Create site configurations
  template:
    src: "{{ item.value.template | default(apache_vhosts_template) }}"
    dest: "/etc/apache2/sites-available/{{ item.value.servername }}.conf"
  with_dict: "{{ apache_vhosts }}"
  notify:
    - create documentroots
    - load apache vhosts
    - restart apache

- name: Create weekly update cron
  cron:
    name: "Update system every Tuesday night at 23:00"
    user: root
    weekday: "2"
    month: "*"
    minute: "*"
    hour: "23"
    day: "*"
    job: "(apt-get update && apt-get -y upgrade) > /dev/null"
    state: present
