---
# Web role tasks

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"

- name: Install Certbot
  apt:
    pkg:
      - certbot
    state: present

- name: Enable Ondrej PHP PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP and some PHP modules
  apt:
    pkg:
      - php8.3
      - php8.3-fpm
      - php8.3-cli
      - php8.3-mysql
      - php8.3-gd
      - php8.3-imagick
      - php8.3-xml
      - php8.3-zip
      - php8.3-intl
      - php8.3-mbstring
      - php8.3-curl
      - php8.3-imap
    state: present

- name: Create Let's Encrypt's live directory
  file:
    path: /etc/letsencrypt/live
    state: directory
    owner: root
    group: root
    mode: 0600

- include: setup-php-fpm.yml
- include: setup-firewall-ids.yml
- include: manage-users.yml

- name: Create weekly update cron
  cron:
    name: "Update system every Tuesday night at 23:00"
    user: root
    weekday: "2"
    month: "*"
    minute: "*"
    hour: "23"
    day: "*"
    job: "(apt-get update && apt-get -y upgrade) > /dev/null"
    state: present

- name: Copy custom SSH config file over
  copy:
    src: roles/web/files/sshd_custom.conf
    dest: /etc/ssh/sshd_config.d/custom.conf
    mode: 0644
    owner: root
    group: root

- name: Make sure SSH uses custom config file
  lineinfile:
    insertafter: "EOF"
    line: "Include sshd_config.d/custom.conf"
    path: /etc/ssh/sshd_config
    state: present
  notify: restart ssh

- name: Only allow ssh for set users
  replace:
    path: /etc/ssh/sshd_config.d/custom.conf
    regexp: '^AllowUsers\s([\s\w][^#\n]+)'
    replace: AllowUsers \1 {{ item.name }}
  loop: "{{linux_users}}"
  when: item.ssh_access == true
  notify: restart ssh