---
# Web role tasks

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"

- name: Install Apache and certbot
  apt:
    pkg:
      - apache2
      - certbot
      - python3-certbot-apache
      - vsftpd
    state: present

- name: Enable mod-rewrite
  shell:
    cmd: a2enmod rewrite
  notify: restart apache

- name: Enable SSL
  shell:
    cmd: a2enmod ssl
  notify: restart apache

- name: Enable Headers module
  shell:
    cmd: a2enmod headers
  notify: restart apache

- name: Enable Ondrej PHP PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP and some PHP modules
  apt:
    pkg:
      - php7.4
      - php7.4-fpm
      - php7.4-cli
      - php7.4-mysql
      - php7.4-gd
      - php7.4-imagick
      - php7.4-xml
      - php7.4-zip
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-curl
      - php7.4-imap
      - php8.2
      - php8.2-fpm
      - php8.2-cli
      - php8.2-mysql
      - php8.2-gd
      - php8.2-imagick
      - php8.2-xml
      - php8.2-zip
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-curl
      - php8.2-imap
    state: present

- name: Create site configurations
  template:
    src: "{{ item.value.template | default(apache_vhosts_template) }}"
    dest: "/etc/apache2/sites-available/{{ item.value.servername }}.conf"
  with_dict: "{{ apache_vhosts }}"
  notify:
    - create documentroots
    - load apache vhosts
    - restart apache

- name: Create Let's Encrypt's live directory
  file:
    path: /etc/letsencrypt/live
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Create certificate directories per vhost
  file:
    path: /etc/letsencrypt/live/{{ item.value.ssldir }}
    state: directory
    owner: root
    group: root
    mode: 0600
  with_dict: "{{ apache_vhosts }}"

- name: Create stub key file per vhost
  template:
    dest: /etc/letsencrypt/live/{{ item.value.ssldir }}/privkey.pem
    src: snakeoil.key
    force: no
    owner: root
    group: root
    mode: 0600
  with_dict: "{{ apache_vhosts }}"

- name: Create stub certificate file per vhost
  template:
    dest: /etc/letsencrypt/live/{{ item.value.ssldir }}/fullchain.pem
    src: snakeoil.pem
    force: no
    owner: root
    group: root
    mode: 0600
  with_dict: "{{ apache_vhosts }}"

- include: setup-php-fpm.yml
- include: setup-firewall-ids.yml
- include: manage-users.yml
- include: setup-vsftp.yml

- name: Create weekly update cron
  cron:
    name: "Update system every Tuesday night at 23:00"
    user: root
    weekday: "2"
    month: "*"
    minute: "*"
    hour: "23"
    day: "*"
    job: "(apt-get update && apt-get -y upgrade) > /dev/null"
    state: present

- name: Copy custom SSH config file over
  copy:
    src: roles/web/files/sshd_custom.conf
    dest: /etc/ssh/sshd_config.d/custom.conf
    mode: 0644
    owner: root
    group: root

- name: Make sure SSH uses custom config file
  lineinfile:
    insertafter: "EOF"
    line: "Include sshd_config.d/custom.conf"
    path: /etc/ssh/sshd_config
    state: present
  notify: restart ssh

- name: Only allow ssh for set users
  replace:
    path: /etc/ssh/sshd_config.d/custom.conf
    regexp: '^AllowUsers\s([\s\w][^#\n]+)'
    replace: AllowUsers \1 {{ item.name }}
  loop: "{{linux_users}}"
  when: item.ssh_access == true
  notify: restart ssh