---
# Create users and groups for the webserver

- name: Setup groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ linux_groups }}"

- name: Manage regular linux users
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    create_home: "{{ item.create_home }}"
  loop: "{{ linux_users }}"
