---
# Setting up VSFTP

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "/etc/ssl/private/vsftpd.pem"
    size: "{{ certvars.key_size }}"
    type: "{{ certvars.key_type }}"
    backup: yes

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  openssl_csr:
    path: "/etc/ssl/private/vsftpd.csr"
    privatekey_path: "/etc/ssl/private/vsftpd.pem"
    country_name: "{{ certvars.country_name }}"
    organization_name: "{{ certvars.organization_name }}"
    email_address: "{{ certvars.email_address }}"
    common_name: "{{ hostname }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "/etc/ssl/private/vsftpd_cert.pem"
    privatekey_path: "/etc/ssl/private/vsftpd.pem"
    csr_path: "/etc/ssl/private/vsftpd.csr"
    provider: selfsigned

- name: Copy empty VSFTP userlist file over
  copy:
    src: roles/web/files/vsftpd.user_list
    dest: /etc/vsftpd.user_list
    mode: 0644
    owner: root
    group: root

- name: Only allow FTP for set users
  lineinfile:
    path: /etc/vsftpd.user_list
    line: "{{ item.name }}"
  loop: "{{linux_users}}"
  when: item.ftp_access == true
  notify: restart vsftp

- name: Enable VSFTP SSL access, restrict FTP to listed users and home directories
  blockinfile:
    path: /etc/vsftpd.conf
    insertafter: EOF
    block: |
      write_enable=YES
      chroot_local_user=YES
      allow_writeable_chroot=YES
      userlist_enable=YES
      userlist_file=/etc/vsftpd.user_list
      userlist_deny=NO
      rsa_cert_file=/etc/ssl/private/vsftpd_cert.pem
      rsa_private_key_file=/etc/ssl/private/vsftpd.pem
      ssl_enable=YES
  notify: restart vsftp