---
# Setup PHP and Apache to use PHP FPM in stead of mod_php

- name: Disable apache MPM prefork
  apache2_module:
    name: mpm_prefork
    state: absent

- name: Enable MPM event module
  apache2_module:
    name: mpm_event
    state: present

- name: Enable FCGI Proxy module
  apache2_module:
    name: proxy_fcgi
    state: present
  notify: restart apache

- name: Create separate PHP FPM pool for each vhost
  template:
    src: "php-pool.conf.j2"
    dest: "/etc/php/{{ item.value.phpver }}/fpm/pool.d/{{ item.value.docroot_owner }}.conf"
  with_dict: "{{ apache_vhosts }}"
  notify:
    - "restart php 7.4"
    - "restart php 7.3"