---
# Mail role handlers

- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart spamass-milter
  service:
    name: spamass-milter
    state: restarted

- name: restart spamassassin
  service:
    name: spamassassin
    state: restarted

- name: Restart spamassassin with daemon reload
  systemd:
    name: spamassassin
    daemon_reload: yes
    state: restarted